# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'FanTong' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FanTong
pod 'YYModel'
pod 'AFNetworking', '~> 3.0'
pod 'RxSwift',    '~> 2.0'
pod 'RxCocoa',    '~> 2.0'
pod 'SDWebImage', '~>3.7'
pod 'TDOAuth'
pod 'YYText'
end
